name: Publish GitHub Package Manually
description: |
  このアクションは、手動で開発中のパッケージをGitHub Packagesに公開します。

  特定のプレリリースタグを用いてバージョン管理し、テストやプレビュー目的で利用されることが想定されています。

  公開するパッケージは、`publish-tag`で指定されたタグ（例: 'next'）を使用して管理されます。

  ## Usage

  ```yaml
  steps:
    - name: Publish development package
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/npm-manual-publish@v0 # This is the version of the action
      with:
        version-type: 'prepatch'
        publish-tag: 'next'
        github-token: 'YOUR_GITHUB_TOKEN'  # ここにGitHub Actionsが提供するデフォルトのトークンを指定
  ```

inputs:
  version-type:
    description: |
      npm version コマンドの引数。
      'prepatch', 'preminor', 'premajor'などの pre release タイプを指定することを想定。
    required: true
  publish-tag:
    description: |
      npm publish コマンドの --tag オプション。
      'latest', 'beta', 'alpha', 'next'などがあります。
      開発中のバージョンをテスト目的で公開する場合は'next'タグが適しています。
    required: true
  github-token:
    description: |
      GitHubトークン
    required: true
  checkout-ref:
    description: |
      チェックアウトするリファレンス
    required: false
    default: ${{ github.head_ref || github.ref }}
  node-version-file:
    description: |
      Node.jsのバージョンを指定するファイルのパス
    required: false
    default: ".nvmrc"
  npm-install-command:
    description: |
      npm install コマンド
    required: false
    default: "ci"

runs:
  using: composite
  steps:
    - name: Inputs summary
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/inputs-summary@v3
      with:
        workflow-inputs: ${{ toJSON(inputs) }}

    - name: Setup Node.js and Install dependencies
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/node-setup-and-dependencies@v3
      with:
        checkout-ref: ${{ inputs.checkout-ref }}
        node-version-file: ${{ inputs.node-version-file }}
        npm-install-command: ${{ inputs.npm-install-command }}
        npm-registry-url: https://npm.pkg.github.com
        npm-scope: "@${{ github.repository_owner }}"
        node-auth-token: ${{ inputs.github-token }}

    # master or main branch (default branch) は 強制pushができないルールにしているため、 master or main branch の場合は version 更新しない
    # default branch 以外の場合は、npm version でバージョンを更新し、コミットする
    - name: Update npm version and commit
      if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/npm-bump-and-commit@v4
      with:
        version-type: ${{ inputs.version-type }}
        skip-checkout: "true"
        skip-node-setup: "true"

    - name: Npm version tag push
      id: tag_version
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/npm-version-tag-push@v4

    - name: Publish to GitHub Packages
      run: |
        set -xeu
        npm publish --tag ${{ inputs.publish-tag }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-token }}

    - name: Create GitHub Release
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/github-release-with-summary@v4
      with:
        version-tag: ${{ steps.tag_version.outputs.tag }}
        github-token: ${{ inputs.github-token }}
