name: Node.js and npm Setup
description: |
  This action sets up Node.js and npm based on specified versions and options.
  It's ideal for creating customizable environments in GitHub Actions workflows.
  The setup includes version management, optional checkout, dependency installation, and npm configuration.

  ## Usage Example

  ### Basic Setup

  ```yaml
  steps:
    - name: Setup Node.js and Install dependencies
      uses: composite/node-npm-setup@v0 # This is the version of the action
      with:
        checkout-ref: <your-checkout-ref> # Use GitHub Actions context
        npm-install-options: '--ignore-scripts --no-audit'
  ```
  This example demonstrates a basic setup where only essential npm install options are specified, ideal for most projects that do not require specific npm configurations.
  It uses common parameters to ensure a smooth installation process without scripts or audit checks.

  ### Npm Configuration

  ```yaml
  steps:
    - name: Setup Node.js and Install dependencies with specific npm settings
      uses: composite/node-npm-setup@v0 # This is the version of the action
      with:
        npm-registry-url: 'https://registry.npmjs.org' # Custom npm registry URL
        npm-scope: '@owner' # Custom scope for npm packages
        node-auth-token: <your-node-auth-token> # Use GitHub Secrets
        npm-install-options: '--ignore-scripts --no-audit'
  ```

  This example is tailored for projects that need to interact with a specific npm registry or have private packages.
  It configures a custom registry URL, a scoped package environment, and authentication using a secret token.
  This setup is crucial for ensuring private packages are handled securely and effectively.

inputs:
  skip-checkout:
    description: |
      Optional input to skip the checkout step.
      The input syntax corresponds to the actions/checkout's one.
    required: false
    default: "false"

  node-version:
    description: |
      Optional input to set the version of Node.js used to build the project.
      The input syntax corresponds to the setup-node's one.
    required: false

  node-version-file:
    description: |
      Optional input to set the file that contains the version of Node.js used to build the project.
      The input syntax corresponds to the setup-node's one.
    required: false
    default: .nvmrc

  node-caching:
    description: |
      Optional input to set up caching for the setup-node action.
      The input syntax corresponds to the setup-node's one.
      Set to an empty string if caching isn't needed.
    required: false
    default: npm

  npm-registry-url:
    description: |
      Optional input to set the registry URL to use for the npm commands.
      The input syntax corresponds to the setup-node's one.
      When using GitHub Packages, specify `https://npm.pkg.github.com`
    required: false
  npm-scope:
    description: |
      Optional input to set the scope to use for the npm commands.
      The input syntax corresponds to the setup-node's one.
      `hoge package` -> `@hoge`
      GitHub Packages -> `@owner` (use `github.repository_owner`)
    required: false

  node-auth-token:
    description: |
      Optional input to set the authentication token to use for the npm commands.
      The input syntax corresponds to the setup-node's one.
      When using GitHub Packages, specify `secrets.GITHUB_TOKEN`
      When using npm, specify `secrets.NPM_AUTH_TOKEN`
    required: false

  checkout-ref:
    description: |
      Optional input to set the ref to checkout.
      The input syntax corresponds to the actions/checkout's one.
    required: false
    # TODO: github.ref?
    default: ${{ github.head_ref }}

  npm-install-command:
    description: |
      Optional input to set the npm command to run.
      `npm ci` -> `ci`
      `npm install` -> `install`
    required: false
    default: "ci"

  npm-install-options:
    description: |
      Optional input to set the options to pass to the `npm ci` or `npm install` command.
      e.g. `--ignore-scripts --no-audit`
    required: false

  create-inputs-summary:
    description: |
      Optional input to create a summary of the inputs used in the workflow.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Create inputs summary
      if: ${{ inputs.create-inputs-summary != 'false' }}
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/inputs-summary@v1
      with:
        workflow-inputs: ${{ toJson(inputs) }}

    - name: Checkout code
      if: ${{ inputs.skip-checkout == 'false' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.checkout-ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file }}
        cache: ${{ inputs.node-caching }}
        registry-url: ${{ inputs.npm-registry-url }}
        scope: ${{ inputs.npm-scope }}

    - name: Install dependencies
      run: npm ${{ inputs.npm-install-command}} ${{ inputs.npm-install-options }}
      shell: bash
      env:
        # CI上では Husky を install しない
        # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
        HUSKY: "0"
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
