name: Node.js and npm Setup
description: |
  This action sets up Node.js and npm for the project.
  Install dependencies using `npm ci`.

inputs:
  skip-checkout:
    description: |
      Optional input to skip the checkout step.
      The input syntax corresponds to the actions/checkout's one.
    required: false
    default: "false"
  node-version:
    description: |
      Optional input to set the version of Node.js used to build the project.
      The input syntax corresponds to the setup-node's one.
    required: false
  node-version-file:
    description: |
      Optional input to set the file that contains the version of Node.js used to build the project.
      The input syntax corresponds to the setup-node's one.
    required: false
    default: .nvmrc
  node-caching:
    description: |
      Optional input to set up caching for the setup-node action.
      The input syntax corresponds to the setup-node's one.
      Set to an empty string if caching isn't needed.
    required: false
    default: npm
  npm-registry-url:
    description: |
      Optional input to set the registry URL to use for the npm commands.
      The input syntax corresponds to the setup-node's one.
      When using GitHub Packages, specify `https://npm.pkg.github.com`
    required: false
  npm-scope:
    description: |
      Optional input to set the scope to use for the npm commands.
      The input syntax corresponds to the setup-node's one.
      `cocone package` -> `@cocone`
      GitHub Packages -> `@owner` (use `github.repository_owner`)
    required: false
  node-auth-token:
    description: |
      Optional input to set the authentication token to use for the npm commands.
      The input syntax corresponds to the setup-node's one.
      When using GitHub Packages, specify `${{ secrets.GITHUB_TOKEN }}`
      When using npm, specify `${{ secrets.NPM_AUTH_TOKEN }}`
    required: false
  checkout-ref:
    description: |
      Optional input to set the ref to checkout.
      The input syntax corresponds to the actions/checkout's one.
    required: false
    # TODO: github.ref?
    default: ${{ github.head_ref }}
  install-options:
    description: |
      Optional input to set the options to pass to the `npm ci` command.
      e.g. `--ignore-scripts --no-audit`
    required: false

runs:
  using: composite
  steps:
    - name: Checkout code
      if: ${{ inputs.skip-checkout == 'false' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.checkout-ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version-file }}
        cache: ${{ inputs.node-caching }}
        registry-url: ${{ inputs.npm-registry-url }}
        scope: ${{ inputs.npm-scope }}

    - name: Install dependencies
      run: npm ci ${{ inputs.install-options }}
      shell: bash
      env:
        # CI上では Husky を install しない
        # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
        HUSKY: "0"
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
