name: Npm Bump from Label
description: |
  このアクションは、GitHubのラベルに基づいてNPMパッケージのバージョンを自動的にアップデートし、更新されたパッケージファイルをリポジトリにプッシュします。

  **Gitタグは作成せず、タグのプッシュも行いません。**

  `release/patch`、`release/minor`、`release/major`のいずれかのラベルがプルリクエストに適用された場合に使用します。

  ## Usage
  以下のようにワークフローに組み込んで使用します。

  `label-name`には、プルリクエストに適用されたバージョン更新用のラベルを指定し、必要に応じて`checkout-ref`を指定して、特定のGitリファレンスから作業を開始することができます。

  ```yaml
  steps:
    - name: Bump version and push package files
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/npm-auto-bump@v0 # This is the version of the action
      with:
        label-name: 'release/patch'
  ```

inputs:
  label-name:
    description: |
      バージョンを更新するラベル名
      release/(patch|minor|major) のいずれかを指定します
    required: true
  checkout-ref:
    description: |
      チェックアウトするリファレンス
    required: false
    default: ${{ github.head_ref || github.ref }}
  node-version-file:
    description: |
      Node.jsのバージョンを指定するファイルのパス
    required: false
    default: ".nvmrc"

runs:
  using: composite
  steps:
    - name: Inputs summary
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/inputs-summary@v3
      with:
        workflow-inputs: ${{ toJSON(inputs) }}

    - name: Check label validity
      run: |
        set -xeu

        label="${{ inputs.label-name }}"
        if [[ ! "$label" =~ ^release/(patch|minor|major)$ ]]; then
          echo "::error::Invalid version label '$label'. Valid labels are 'release/patch', 'release/minor', and 'release/major'."
          exit 1
        fi
      shell: bash

    - name: Version from label
      id: version
      run: |
        set -xeu

        version_label="$(echo "${{ inputs.label-name }}" | cut -d'/' -f2)"
        echo "Bumping version to $version_label"
        echo "version_label=$version_label" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Npm bump and commit
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/npm-bump-and-commit@v4
      with:
        version-type: ${{ steps.version.outputs.version_label }}
        checkout-ref: ${{ inputs.checkout-ref }}
        node-version-file: ${{ inputs.node-version-file }}
