name: Setup Environment Variables
description: |
  This action sets up environment variables for the project.
  Set environment variables using a space-separated string.
  For example, 'TEST="abc" URL="http://agalkjgaljgalkjglag" SEPARATED_VALUE="abc def"'

inputs:
  environment-variables:
    description: |
      Required input to set the environment variables.
      Environment variables as a space-separated string (e.g., 'TEST="abc" URL="http://example.com" SERVICE="app"')
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate and Set Environment Variables
      run: |
        set -x
        set -e

        # 入力値をシングルクォーテーションで囲むことで、文字列がそのまま保持されるようにする。
        # GitHub Actionsの式展開を避けて、入力された文字列がスクリプト内で正確に解析されるようにするため。
        env_vars='${{ inputs.environment-variables }}'
        echo "$env_vars"

        # 正規表現を使ってキーと値を抽出
        echo "$env_vars" | grep -oP '(?:\w+="[^"]+")' | while IFS='=' read -r key value; do
          # キーが環境変数として適切かチェック
          if [[ "$key" =~ ^[A-Za-z_][A-Za-z_0-9]*$ ]]; then
            # 値から引用符を削除
            value="${value%\"}"
            value="${value#\"}"
            echo "Setting: $key=$value"
            echo "$key=$value" >> "$GITHUB_ENV"
          else
            echo "Error: Invalid key format '$key'"
          fi
        done
      shell: bash
