name: Create GitHub Release
description: |
  このアクションは、GitHub CLIを使用してGitHubリリースを作成し、オプションでジョブサマリーにリリース情報を出力します。

  ## Usage

  ```yaml
  steps:
    - name: Create GitHub Release
      uses: gawaooooo-sandbox/learn-github-actions-custom/composite/github-release-with-summary@v0 # This is the version of the action
      with:
        version-tag: 'v1.0.0'
        github-token: 'YOUR_GITHUB_TOKEN'  # ここにGitHub Actionsが提供するデフォルトのトークンを指定
  ```

inputs:
  version-tag:
    description: リリースに使用するバージョンタグ
    required: true
  github-token:
    description: GitHubアクションのトークン
    required: true
  summary-output:
    description: ジョブサマリーにリリース情報を出力するかどうか
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Create Release
      run: |
        set -xeu
        gh release create ${{ inputs.version-tag }} --title ${{ inputs.version-tag }} --generate-notes
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Append release success to job summary
      if: success() && ${{ fromJSON(inputs.summary-output) }}
      run: |
        {
          echo "## Release Details ✨"
          echo "Release for version ${{ inputs.version-tag }} was successfully created. 🎉"
          echo "You can view the release [here](https://github.com/${{ github.repository }}/releases/tag/${{ inputs.version-tag }})."
        } >> "$GITHUB_STEP_SUMMARY"
      shell: bash
