name: Inputs Summary
description: |
  This action creates a summary of the inputs provided to the workflow.

inputs:
  workflow-inputs:
    description: |
      The inputs provided to the workflow.
      Passing the inputs context wrapped in a `toJSON` expression.
    required: true

runs:
  using: composite
  steps:
    - name: Create Inputs Summary
      uses: actions/github-script@v7
      with:
        script: |
          const { INPUTS: _inputs } = process.env;
          console.log(typeof _inputs);
          console.log(_inputs);

          let inputs;
          // _inputs の型がstringの場合はJSON.parseする
          if (typeof _inputs === 'string') {
            inputs = JSON.parse(_inputs);
          } else {
            inputs = _inputs;
          }

          // const inputs = JSON.parse(process.env.INPUTS);
          console.log(inputs);

          const parametersTable = [
            [{ data: 'key', header: true}, { data: 'value', header: true }],
            ['branch', '${{ github.ref_name }}']
          ];

          for ([key, value] of Object.entries(inputs)) {
          console.log(key, value);
            parametersTable.push([key, value])
          }

          await core.summary
            .addRaw("### 📝 Inputs \n")
            .addTable(parametersTable)
            .write()
      env:
        INPUTS: ${{ inputs.workflow-inputs }}
