name: Inputs Summary
description: |
  This action creates a summary of the inputs provided to the workflow.

inputs:
  workflow-inputs:
    description: |
      The inputs provided to the workflow.
      Passing the inputs context wrapped in a `toJSON` expression.
    required: true

runs:
  using: composite
  steps:
    - name: Create Inputs Summary
      uses: actions/github-script@v7
      with:
        script: |
          const inputsStr = process.env.INPUTS;
          console.log(typeof inputsStr);
          console.log(inputsStr);

          // 文字列をJSONオブジェクトに変換
          const inputs = JSON.parse(inputsStr);
          console.log(inputs);

          const parametersTable = [
            [{ data: 'key', header: true}, { data: 'value', header: true }],
            ['branch', '${{ github.ref_name }}']
          ];

          for ([key, value] of Object.entries(inputs)) {
            // boolean値と数値を文字列に変換する
            const valueStr = typeof value === 'boolean' || typeof value === 'number' ? value.toString() : value;
            parametersTable.push([key, valueStr])
          }

          await core.summary
            .addRaw("### 📝 Inputs \n")
            .addTable(parametersTable)
            .write()
      env:
        INPUTS: ${{ inputs.workflow-inputs }}
