name: Setup Deployment Config
description: |
  This action is essential for configuring deployment settings within your GitHub workflow.
  It initializes necessary environment variables and an S3 sync command to effectively manage deployments to an AWS S3 bucket.

  The `build-environments` input allows you to set a series of environment variables which are crucial for the build and deployment process, formatted as space-separated key-value pairs.
  This setup enables subsequent steps or jobs in your GitHub Actions workflow to access these variables reliably, ensuring consistency across different environments.

  The `s3-sync-command` input allows you to specify the exact command line string for synchronizing your project's files to an S3 bucket.
  This capability is vital for ensuring that your deployment's state remains consistent with your current project build.

  Here’s how you can use this action in your workflow:

  ## Usage Example

  ```yaml
  steps:
    - name: Setup Deployment Config
      uses: ./composite/setup-deployment-config@v0 # This is the version of the action
      with:
        build-environments: >-
          BASE_URL="http://example.com"
          SERVICE="app:test"
          SPACE_SEPARATED="one two three"
        s3-sync-command: ./dist s3://my-bucket --delete --dryrun --exclude "*.log" --exclude "test/*"
  ```

inputs:
  build-environments:
    description: |
      Sets environment variables for the build process.
      Provide a string of key-value pairs separated by spaces, e.g., 'BASE_URL="http://example.com" SERVICE="app"'.
    required: false
    default: ""

  s3-sync-command:
    description: |
      Specifies the command to sync files to an S3 bucket.
      Format it as a full command line string, e.g., './dist s3://my-bucket --delete'.
    required: true

outputs:
  build-environments:
    description: |
      Returns the set build environment variables as a string of key-value pairs.
    value: ${{ steps.setup-build-environments.outputs.build-environments }}

  s3-sync-command:
    description: |
      Returns the formatted command used for syncing files to the S3 bucket.
    value: ${{ steps.setup-s3-sync-command.outputs.s3-sync-command }}

runs:
  using: composite
  steps:
    - name: Setup Build Environments [${{ inputs.build-environments }}]
      id: setup-build-environments
      run: |
        set -xeu

        # 入力値をシングルクォーテーションで囲むことで、文字列がそのまま保持されるようにする。
        # GitHub Actionsの式展開を避けて、入力された文字列がスクリプト内で正確に解析されるようにするため。
        build_vars='${{ inputs.build-environments }}'
        echo "build-environments=$build_vars" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Validate and Setup S3 Deploy Command [${{ inputs.s3-sync-command }}]
      id: setup-s3-sync-command
      run: |
        set -xeu

        s3_command='${{ inputs.s3-sync-command }}'
        # Validate the input to make sure it does not contain any shell control characters
        if [[ "$s3_command" =~ [\;\&\|] ]]; then
          echo "Error: Invalid characters in S3 sync command"
          exit 1
        fi

        echo "s3-sync-command=$s3_command" >> "$GITHUB_OUTPUT"
      shell: bash
