name: Setup Deployment Config
description: |
  This action sets up the deployment configuration for the project by configuring build environments and preparing the S3 sync command.
  Use the `build-environments` input to set environment variables in the format `KEY=VALUE` separated by spaces (e.g., 'BASE_URL="http://example.com" "SERVICE=app"').
  Use the `s3-sync-command` input to specify the command for syncing files to an S3 bucket, including any necessary flags.

inputs:
  build-environments:
    description: |
      Required input to set the build environments.
      Specify as a space-separated string of key-value pairs (e.g., 'BASE_URL="http://example.com" SERVICE="app"').
    required: true

  s3-sync-command:
    description: |
      The command to sync files to the S3 bucket, formatted as a command line string.
      Example: './dist s3://my-bucket --delete'
    required: true

outputs:
  build-environments:
    description: |
      The build environments for the project, returned as a string of key-value pairs.
    value: ${{ steps.setup-build-environments.outputs.build-environments }}

  s3-sync-command:
    description: |
      The command used to sync files to the S3 bucket, formatted as a command line string.
    value: ${{ steps.setup-s3-sync-command.outputs.s3-sync-command }}

runs:
  using: composite
  steps:
    - name: Setup Build Environments [${{ inputs.build-environments }}]
      id: setup-build-environments
      run: |
        set -x

        # 入力値をシングルクォーテーションで囲むことで、文字列がそのまま保持されるようにする。
        # GitHub Actionsの式展開を避けて、入力された文字列がスクリプト内で正確に解析されるようにするため。
        build_vars='${{ inputs.build-environments }}'
        echo "build-environments=$build_vars" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Setup S3 Deploy Command [${{ inputs.s3-sync-command }}]
      id: setup-s3-sync-command
      run: |
        set -x
        # コマンドラインをエスケープ
        s3_command=$(echo '${{ inputs.s3-sync-command }}' | sed 's/"/\\"/g')
        echo "s3-sync-command=$s3_command" >> "$GITHUB_OUTPUT"
      shell: bash
