name: Test for setup-deployment-config
run-name: ${{ github.workflow }} on ${{ github.ref_type }} ${{ github.ref_name }} [${{ github.sha }}]

on:
  pull_request:
    paths:
      - "composite/setup-deployment-config/action.yml"
      - ".github/workflows/_internal-test-setup-deployment-config.yml"
  workflow_dispatch:

concurrency:
  group: test-setup-deployment-config-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test-setup-deployment-config:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      ENV_VALUE: 123:456:789

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Exercise
        id: setup-deployment-config
        uses: ./composite/setup-deployment-config
        with:
          build-environments: >-
            BASE_URL="http://example.com"
            SERVICE="app:test"
            SPACE_SEPARATED="one two three"
            ENV_VALUE_TEST="${{ env.ENV_VALUE }}"
          s3-sync-command: ./dist s3://my-bucket --delete --dryrun --exclude "*.log" --exclude "test/*"

      - name: Verify Build Environments
        run: |
          set -x

          # Outputs are fetched from the action's output, encapsulated in single quotes to preserve the integrity of the data.
          actual='${{ steps.setup-deployment-config.outputs.build-environments }}'

          # Expected string must match the exact format that the action outputs.
          expected='BASE_URL="http://example.com" SERVICE="app:test" SPACE_SEPARATED="one two three" ENV_VALUE_TEST="123:456:789"'

          echo "Actual: $actual"
          echo "Expected: $expected"

          if [ "$expected" != "$actual" ]; then
            echo "Failure: Build environments do not match expected values."
            exit 1
          else
            echo "Success: Build environments match expected values."
          fi

      - name: Verify S3 Sync Command
        run: |
          set -x

          # Outputs are fetched from the action's output, encapsulated in single quotes to preserve the integrity of the data.
          actual='${{ steps.setup-deployment-config.outputs.s3-sync-command }}'
          expected='./dist s3://my-bucket --delete --dryrun --exclude "*.log" --exclude "test/*"'

          echo "Actual: $actual"
          echo "Expected: $expected"

          if [ "$expected" != "$actual" ]; then
            echo "Failure: S3 sync command does not match expected values."
            exit 1
          else
            echo "Success: S3 sync command matches expected values."
          fi

  # build-environments が指定されていない場合のテスト
  test-setup-deployment-config-no-build-environments:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Exercise
        id: setup-deployment-config
        uses: ./composite/setup-deployment-config
        with:
          s3-sync-command: ./dist s3://my-bucket --delete --dryrun --exclude "*.log" --exclude "test/*"

      - name: Verify Build Environments
        run: |
          set -x

          # Outputs are fetched from the action's output, encapsulated in single quotes to preserve the integrity of the data.
          actual='${{ steps.setup-deployment-config.outputs.build-environments }}'

          # Expected string must match the exact format that the action outputs.
          expected=''

          echo "Actual: $actual"
          echo "Expected: $expected"

          if [ "$expected" != "$actual" ]; then
            echo "Failure: Build environments do not match expected values."
            exit 1
          else
            echo "Success: Build environments match expected values."
          fi

      - name: Verify S3 Sync Command
        run: |
          set -x

          # Outputs are fetched from the action's output, encapsulated in single quotes to preserve the integrity of the data.
          actual='${{ steps.setup-deployment-config.outputs.s3-sync-command }}'
          expected='./dist s3://my-bucket --delete --dryrun --exclude "*.log" --exclude "test/*"'

          echo "Actual: $actual"
          echo "Expected: $expected"

          if [ "$expected" != "$actual" ]; then
            echo "Failure: S3 sync command does not match expected values."
            exit 1
          else
            echo "Success: S3 sync command matches expected values."
          fi
