name: Internal Label
run-name: "${{ github.workflow }} for ${{ github.ref_name }} [${{ github.sha }}]"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call:
    uses: gawaooooo-sandbox/learn-github-actions-reusable-workflows/.github/workflows/label.yml@v4
    permissions:
      contents: read
      pull-requests: write
