name: Generate actions docs
run-name: "${{ github.workflow }} for ${{ github.ref_name }} Triggered by: ${{ github.event_name }} [${{ github.sha }}]"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "composite/**/action.yml"
      - ".github/workflows/_internal-docs.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  generate:
    uses: gawaooooo-sandbox/learn-github-actions-reusable-workflows/.github/workflows/docs-generator.yml@v3
    with:
      doc-type: composite
      commit-message: Update composite action document
    permissions:
      contents: write
      pull-requests: write
