name: Test for node-setup-and-dependencies
run-name: ${{ github.workflow }} on ${{ github.ref_type }} ${{ github.ref_name }} [${{ github.sha }}]

on:
  pull_request:
    paths:
      - "composite/node-setup-and-dependencies/action.yml"
      - ".github/workflows/_internal-test-node-setup-and-dependencies.yml"
  workflow_dispatch:

concurrency:
  group: test-node-setup-and-dependencies-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          pwd
          ls -la

      - name: Exercise
        uses: ./composite/node-setup-and-dependencies
        with:
          # skip-checkout: "true"
          npm-install-command: "install"
          npm-install-options: "--ignore-scripts"
          create-inputs-summary: "true"

      - name: Verify
        run: |
          ls -la
          test -d "node_modules"
