name: Test for inputs-summary
run-name: ${{ github.workflow }} on ${{ github.ref_type }} ${{ github.ref_name }} [${{ github.sha }}]

on:
  pull_request:
    paths:
      - "composite/inputs-summary/action.yml"
      - ".github/workflows/test-inputs-summary.yml"
  workflow_dispatch:

concurrency:
  group: test-inputs-summary-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        id: workflow-inputs
        run: |
          inputs=$(echo '{"foo":"bar","hoge":"fuga"}' | jq -c)
          echo "inputs=${inputs}" >> "$GITHUB_OUTPUT"

      - name: Output
        run: |
          echo "---- steps.workflow-inputs.outputs.inputs ----"
          echo "${{ steps.workflow-inputs.outputs.inputs }}"
          echo "---- steps.workflow-inputs.outputs.inputs (fromJSON) ----"
          echo "${{ fromJSON(steps.workflow-inputs.outputs.inputs) }}"
          echo "---- steps.workflow-inputs.outputs.inputs (toJSON) ----"
          echo "${{ toJSON(steps.workflow-inputs.outputs.inputs) }}"

      - name: Exercise
        uses: ./composite/inputs-summary
        with:
          # workflow-inputs: ${{ toJSON(steps.workflow-inputs.outputs.inputs) }}
          workflow-inputs: ${{ steps.workflow-inputs.outputs.inputs }}
